<!DOCTYPE html>
<html class="scroll-smooth" lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Curated Experiences | Praisty Resort</title>
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..900&amp;family=Hanken+Grotesk:ital,wght@0,100..900;1,400..900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <script>
        tailwind.config = { theme: { extend: { colors: { background: '#fbf9f4', surface: '#fbf9f4', 'surface-container': '#f0eee9', 'surface-container-low': '#f5f3ee', 'surface-container-lowest': '#ffffff', 'surface-container-highest': '#e4e2dd', 'surface-variant': '#e4e2dd', primary: '#001e40', 'primary-container': '#003366', 'on-primary': '#ffffff', 'primary-fixed': '#d5e3ff', 'on-primary-fixed-variant': '#1f477b', secondary: '#3b6934', 'secondary-fixed': '#bcf0ae', 'on-surface': '#1b1c19', 'on-surface-variant': '#43474f' }, spacing: { 'section-gap': '120px', 'margin-mobile': '20px', gutter: '24px', 'container-max': '1280px', 'margin-desktop': '64px' }, fontFamily: { 'display-lg': ['EB Garamond', 'serif'], 'headline-lg': ['EB Garamond', 'serif'], 'headline-md': ['EB Garamond', 'serif'], 'body-md': ['Hanken Grotesk', 'sans-serif'], 'body-lg': ['Hanken Grotesk', 'sans-serif'], 'label-md': ['Hanken Grotesk', 'sans-serif'] }, fontSize: { 'display-lg': ['64px', { lineHeight: '72px', fontWeight: '400' }], 'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '500' }], 'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }], 'body-md': ['16px', { lineHeight: '24px' }], 'body-lg': ['18px', { lineHeight: '28px' }], 'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }] } } } };
    </script>
    <style>
        .material-symbols-outlined { font-variation-settings: 'FILL' 0, 'wght' 300, 'GRAD' 0, 'opsz' 24; }
        .soft-shadow { box-shadow: 0 20px 40px -10px rgba(0, 30, 64, .05); }
        .experience-card { transition: transform .4s cubic-bezier(.16, 1, .3, 1), box-shadow .4s cubic-bezier(.16, 1, .3, 1); }
        .experience-card:hover { box-shadow: 0 30px 60px -15px rgba(0, 30, 64, .12); transform: translateY(-8px); }
        .experience-card img { transition: transform .8s cubic-bezier(.16, 1, .3, 1); }
        .experience-card:hover img { transform: scale(1.05); }
    </style>
</head>
<body class="overflow-x-hidden bg-background font-body-md text-on-surface antialiased">
<nav class="fixed top-0 z-50 w-full bg-surface/90 shadow-sm backdrop-blur-md" id="main-nav"><div class="mx-auto flex max-w-container-max items-center justify-between px-margin-mobile py-4 md:px-margin-desktop"><a class="font-headline-md text-headline-md tracking-widest text-primary uppercase" href="{{ route('home') }}">Praisty Resort</a><div class="hidden items-center space-x-8 md:flex"><a class="font-label-md text-label-md text-on-surface-variant hover:text-primary" href="{{ route('home') }}">Home</a><a class="font-label-md text-label-md text-on-surface-variant hover:text-primary" href="{{ route('rooms') }}">Rooms &amp; Villas</a><a class="border-b border-primary pb-1 font-label-md text-label-md text-primary" href="{{ route('experiences') }}">Experiences</a><a class="font-label-md text-label-md text-on-surface-variant hover:text-primary" href="{{ route('gallery') }}">Gallery</a><a class="font-label-md text-label-md text-on-surface-variant hover:text-primary" href="{{ route('contact') }}">Contact</a></div><a class="hidden rounded bg-primary-container px-6 py-3 font-label-md text-label-md text-on-primary uppercase transition-transform hover:scale-105 md:inline-flex" href="{{ route('rooms') }}#room-search">Book Now</a><button aria-controls="mobile-menu" aria-expanded="false" aria-label="Open navigation menu" class="p-2 text-primary md:hidden" id="mobile-menu-button" type="button"><span class="material-symbols-outlined">menu</span></button></div><div class="hidden border-t border-surface-container-highest bg-surface px-margin-mobile py-5 md:hidden" id="mobile-menu"><div class="flex flex-col gap-4 font-label-md text-label-md text-primary"><a href="{{ route('home') }}">Home</a><a href="{{ route('rooms') }}">Rooms &amp; Villas</a><a href="{{ route('experiences') }}">Experiences</a><a href="{{ route('gallery') }}">Gallery</a><a href="{{ route('contact') }}">Contact</a></div></div></nav>

<header class="mx-auto max-w-container-max px-margin-mobile pb-24 pt-[150px] text-center md:px-margin-desktop md:pb-32 md:pt-[190px]"><h1 class="mb-6 font-display-lg text-display-lg text-primary max-md:text-5xl">Curated Experiences</h1><p class="mx-auto max-w-2xl font-body-lg text-body-lg text-on-surface-variant">Discover a world of refined tranquility and exhilarating adventure. From serene spa rituals to sunset sailing, every moment at Praisty Resort is designed to elevate your stay and create lasting memories.</p></header>

<main class="mx-auto max-w-container-max px-margin-mobile pb-section-gap md:px-margin-desktop"><div class="grid grid-cols-1 gap-gutter md:grid-cols-12">
    <article class="experience-card soft-shadow mb-gutter overflow-hidden rounded-xl bg-surface-container-lowest md:col-span-12"><div class="h-full md:flex"><div class="relative h-96 overflow-hidden md:h-auto md:w-1/2"><img alt="Oceanfront spa ritual at Praisty Resort" class="absolute inset-0 h-full w-full object-cover" src="{{ asset('images/resort/sanctuary-spa.png') }}"></div><div class="flex flex-col justify-center bg-surface-container-lowest p-8 md:w-1/2 md:p-16"><span class="mb-4 w-fit rounded-full bg-surface-container px-3 py-1 text-xs font-label-md uppercase tracking-wider text-primary">Wellness</span><h2 class="mb-4 font-headline-lg text-headline-lg text-primary">Oceanfront Spa Rituals</h2><p class="mb-8 text-on-surface-variant">Surrender to the rhythm of the waves as our expert therapists restore your balance. Indigenous botanical ingredients and ancient healing techniques turn every bespoke treatment into a profound renewal.</p><div class="mt-auto flex flex-col gap-4 border-t border-surface-variant pt-6 sm:flex-row sm:items-center sm:justify-between"><div class="flex flex-wrap gap-x-4 gap-y-2 text-on-surface-variant"><span class="flex items-center"><span class="material-symbols-outlined mr-2 text-[20px]">schedule</span>90 - 120 Min</span><span class="flex items-center"><span class="material-symbols-outlined mr-2 text-[20px]">payments</span>From &#8369;14,000</span></div><a class="inline-flex items-center font-label-md text-label-md uppercase tracking-wider text-primary hover:text-secondary" href="{{ route('rooms') }}#room-search">Inquire Now <span class="material-symbols-outlined ml-2">arrow_forward</span></a></div></div></div></article>
    <article class="experience-card soft-shadow flex h-[600px] flex-col overflow-hidden rounded-xl bg-surface-container-lowest md:col-span-7"><div class="relative h-2/3 flex-grow overflow-hidden"><img alt="Private sunset dining at Praisty Resort" class="absolute inset-0 h-full w-full object-cover" src="{{ asset('images/resort/tide-table-dining.png') }}"></div><div class="flex h-1/3 flex-col justify-between bg-surface-container-lowest p-8"><div><div class="mb-2 flex items-start justify-between gap-4"><h3 class="font-headline-md text-headline-md text-primary">Private Sunset Dining</h3><span class="shrink-0 rounded-full bg-surface-container px-3 py-1 text-xs font-label-md uppercase tracking-wider text-primary">Culinary</span></div><p class="line-clamp-2 text-on-surface-variant">An unforgettable tasting menu on the secluded shores of Praisty Resort, paired with exquisite wines as the sun dips below the horizon.</p></div><div class="flex items-center justify-between border-t border-surface-variant pt-4 text-sm"><span class="flex items-center text-on-surface-variant"><span class="material-symbols-outlined mr-1 text-[18px]">schedule</span>Evening</span><a class="inline-flex items-center font-label-md text-label-md uppercase tracking-wider text-primary hover:text-secondary" href="{{ route('rooms') }}#room-search">Inquire Now <span class="material-symbols-outlined ml-1 text-[18px]">arrow_forward</span></a></div></div></article>
    <article class="experience-card soft-shadow flex h-[600px] flex-col overflow-hidden rounded-xl bg-surface-container-lowest md:col-span-5"><div class="relative h-1/2 flex-grow overflow-hidden"><img alt="Morning wellness ritual beside the ocean" class="absolute inset-0 h-full w-full object-cover" src="{{ asset('images/resort/overwater-wellness-ritual.png') }}"></div><div class="flex h-1/2 flex-col justify-between bg-surface-container-lowest p-8"><div><div class="mb-2 flex items-start justify-between gap-4"><h3 class="font-headline-md text-headline-md text-primary">Sunrise Yoga</h3><span class="shrink-0 rounded-full bg-surface-container px-3 py-1 text-xs font-label-md uppercase tracking-wider text-primary">Wellness</span></div><p class="line-clamp-3 text-on-surface-variant">Awaken your senses with guided Hatha and Vinyasa sessions in an open-air pavilion, focused on breath, movement, and mindful presence.</p></div><div class="flex items-center justify-between border-t border-surface-variant pt-4 text-sm"><span class="flex items-center text-on-surface-variant"><span class="material-symbols-outlined mr-1 text-[18px]">schedule</span>60 Min</span><a class="inline-flex items-center font-label-md text-label-md uppercase tracking-wider text-primary hover:text-secondary" href="{{ route('rooms') }}#room-search">Inquire Now <span class="material-symbols-outlined ml-1 text-[18px]">arrow_forward</span></a></div></div></article>
</div></main>

<footer class="bg-primary pb-8 pt-section-gap text-on-primary"><div class="mx-auto grid max-w-container-max grid-cols-1 gap-gutter px-margin-mobile md:grid-cols-4 md:px-margin-desktop"><div class="md:col-span-2"><a class="mb-4 block font-headline-md text-headline-md tracking-widest" href="{{ route('home') }}">PRAISTY RESORT</a><p class="max-w-sm text-primary-fixed">A sanctuary of modern luxury nestled in the heart of the tropics. Experience unparalleled service and raw natural beauty.</p></div><div><h4 class="mb-4 text-xs font-label-md uppercase tracking-wider text-secondary-fixed">Resort</h4><a class="text-primary-fixed hover:text-on-primary" href="{{ route('rooms') }}">Rooms &amp; Villas</a></div><div><h4 class="mb-4 text-xs font-label-md uppercase tracking-wider text-secondary-fixed">Connect</h4><a class="text-primary-fixed hover:text-on-primary" href="{{ route('contact') }}">Contact Us</a></div></div><div class="mx-auto mt-16 max-w-container-max border-t border-primary-fixed/30 px-margin-mobile pt-8 text-sm text-primary-fixed md:px-margin-desktop">&copy; {{ date('Y') }} Praisty Resort &amp; Spa. All rights reserved.</div></footer>
<script src="{{ asset('js/app.js') }}?v=202609271410"></script><script>const menuButton=document.getElementById('mobile-menu-button');const mobileMenu=document.getElementById('mobile-menu');menuButton?.addEventListener('click',()=>{const hidden=mobileMenu.classList.toggle('hidden');menuButton.setAttribute('aria-expanded',String(!hidden));});</script>
</body>
</html>
