<!DOCTYPE html>
<html class="scroll-smooth" lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="{{ csrf_token() }}" name="csrf-token">
    <title>Guest &amp; Payment | Praisty Resort</title>
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..900&amp;family=Hanken+Grotesk:ital,wght@0,100..900;1,400..900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <script>tailwind.config={theme:{extend:{colors:{background:'#fbf9f4',surface:'#fbf9f4','surface-container-low':'#f5f3ee','surface-container-high':'#eae8e3','surface-container-highest':'#e4e2dd',primary:'#001e40','primary-container':'#003366','on-primary':'#ffffff','primary-fixed':'#d5e3ff',secondary:'#3b6934','secondary-container':'#b9eeab','on-secondary-container':'#3f6d38','on-surface':'#1b1c19','on-surface-variant':'#43474f',outline:'#737780','outline-variant':'#c3c6d1'},spacing:{'margin-mobile':'20px','container-max':'1280px','margin-desktop':'64px'},fontFamily:{display:['EB Garamond','serif'],headline:['EB Garamond','serif'],body:['Hanken Grotesk','sans-serif']}}}};</script>
</head>
<body class="min-h-screen bg-background font-body text-on-surface antialiased">
<nav class="fixed top-0 z-50 w-full bg-surface/90 shadow-sm backdrop-blur-md" id="main-nav"><div class="mx-auto flex max-w-container-max items-center justify-between px-margin-mobile py-4 md:px-margin-desktop"><a class="font-headline text-[28px] tracking-widest text-primary uppercase" href="{{ route('home') }}">Praisty Resort</a><div class="hidden items-center space-x-8 text-sm font-semibold tracking-wide md:flex"><a class="text-on-surface-variant hover:text-primary" href="{{ route('home') }}">Home</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('rooms') }}">Rooms &amp; Villas</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('experiences') }}">Experiences</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('gallery') }}">Gallery</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('contact') }}">Contact</a></div><a class="hidden rounded bg-primary-container px-6 py-3 text-sm font-semibold uppercase tracking-wide text-on-primary md:inline-flex" href="{{ route('reservation.cart') }}">Reservation Cart</a><button aria-controls="mobile-menu" aria-expanded="false" aria-label="Open navigation menu" class="p-2 text-primary md:hidden" id="mobile-menu-button" type="button"><span class="material-symbols-outlined">menu</span></button></div><div class="hidden border-t border-outline-variant bg-surface px-margin-mobile py-5 md:hidden" id="mobile-menu"><div class="flex flex-col gap-4 text-sm font-semibold text-primary"><a href="{{ route('home') }}">Home</a><a href="{{ route('rooms') }}">Rooms &amp; Villas</a><a href="{{ route('experiences') }}">Experiences</a><a href="{{ route('gallery') }}">Gallery</a><a href="{{ route('contact') }}">Contact</a></div></div></nav>

<main class="mx-auto max-w-container-max px-margin-mobile pb-24 pt-28 md:px-margin-desktop md:pt-32"><div class="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-center"><nav aria-label="Breadcrumb" class="flex items-center gap-2 text-sm text-on-surface-variant"><a class="hover:text-primary" href="{{ route('reservation.cart') }}">Reservation Cart</a><span>/</span><span class="text-primary">Guest &amp; Payment</span></nav><div class="flex w-fit items-center gap-3 rounded-full bg-surface-container-low px-4 py-2 text-xs font-semibold"><span class="flex items-center gap-1.5 text-secondary"><span class="material-symbols-outlined text-base">check_circle</span>1. Villa</span><span class="h-px w-4 bg-outline-variant"></span><span class="flex items-center gap-1.5 text-secondary"><span class="material-symbols-outlined text-base">check_circle</span>2. Review</span><span class="h-px w-4 bg-outline-variant"></span><span class="flex items-center gap-1.5 text-primary"><span class="flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[10px] text-on-primary">3</span>Guest &amp; Payment</span></div></div>
    <div class="grid grid-cols-1 items-start gap-8 lg:grid-cols-12"><section class="lg:col-span-8"><div class="rounded-xl bg-white p-6 shadow-sm md:p-8"><p class="mb-2 text-xs font-semibold uppercase tracking-widest text-secondary">Final Step</p><h1 class="font-headline text-4xl text-primary md:text-5xl">Guest &amp; Payment</h1><p class="mt-3 max-w-2xl text-on-surface-variant">Tell us who will be staying at Praisty Resort and choose how you would like to settle your reservation.</p>
        @if (session('reservation_complete'))
            <div class="mt-6 rounded-lg border border-secondary/30 bg-secondary-container/40 p-4 text-on-secondary-container" role="status">{{ session('reservation_complete') }}</div>
        @endif
        @if ($errors->any())
            <div class="mt-6 rounded-lg border border-red-300 bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Please check your details.</p><ul class="mt-1 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
        @endif
        <form action="{{ route('reservation.complete') }}" class="mt-8 space-y-10" method="POST">@csrf
            <fieldset><legend class="font-headline text-3xl text-primary">Lead Guest Details</legend><div class="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2"><label class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant sm:col-span-2">Full name<input class="mt-2 w-full rounded border-outline-variant bg-surface px-4 py-3 text-base normal-case text-on-surface focus:border-primary focus:ring-primary" name="full_name" required type="text" value="{{ old('full_name', session('guest_reservation.full_name')) }}"></label><label class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Email address<input class="mt-2 w-full rounded border-outline-variant bg-surface px-4 py-3 text-base normal-case text-on-surface focus:border-primary focus:ring-primary" name="email" required type="email" value="{{ old('email', session('guest_reservation.email')) }}"></label><label class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Mobile number<input class="mt-2 w-full rounded border-outline-variant bg-surface px-4 py-3 text-base normal-case text-on-surface focus:border-primary focus:ring-primary" name="phone" placeholder="+63 900 000 0000" required type="tel" value="{{ old('phone') }}"></label><label class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Country / region<select class="mt-2 w-full rounded border-outline-variant bg-surface px-4 py-3 text-base normal-case text-on-surface focus:border-primary focus:ring-primary" name="country" required><option disabled @selected(!old('country')) value="">Select country / region</option><option @selected(old('country') === 'Philippines') value="Philippines">Philippines</option><option @selected(old('country') === 'Australia') value="Australia">Australia</option><option @selected(old('country') === 'United States') value="United States">United States</option><option @selected(old('country') === 'Other') value="Other">Other</option></select></label><label class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Special request <span class="normal-case font-normal">(optional)</span><input class="mt-2 w-full rounded border-outline-variant bg-surface px-4 py-3 text-base normal-case text-on-surface focus:border-primary focus:ring-primary" name="special_request" placeholder="Arrival notes, dietary needs, celebrations" type="text" value="{{ old('special_request') }}"></label></div></fieldset>
            <fieldset class="border-t border-surface-container-highest pt-8"><legend class="font-headline text-3xl text-primary">Payment Preference</legend><p class="mt-2 text-sm text-on-surface-variant">Choose your preferred payment method. Your concierge will send the official payment instructions after confirming availability.</p><div class="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3">@foreach ($paymentOptions as $value => $option)<label class="payment-option cursor-pointer rounded-lg border border-outline-variant bg-surface p-4 transition-colors has-[:checked]:border-primary has-[:checked]:bg-primary-fixed/40"><input class="sr-only" @checked($selectedPaymentMethod === $value) name="payment_method" required type="radio" value="{{ $value }}"><span class="material-symbols-outlined text-primary">{{ $option['icon'] }}</span><span class="mt-3 block font-semibold text-primary">{{ $option['label'] }}</span><span class="mt-1 block text-xs text-on-surface-variant">{{ $option['summary'] }}</span></label>@endforeach</div></fieldset>
            <button class="flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-4 text-sm font-semibold uppercase tracking-widest text-on-primary transition-all hover:scale-[1.01] hover:bg-primary-container" type="submit">Confirm Reservation Request <span class="material-symbols-outlined text-lg">arrow_forward</span></button>
        </form></div></section>
        <aside class="lg:col-span-4"><div class="sticky top-28 rounded-xl bg-white p-6 shadow-md"><h2 class="font-headline text-3xl text-primary">Stay Summary</h2><div class="my-5 overflow-hidden rounded-lg"><img class="h-36 w-full object-cover" src="{{ asset($room['image']) }}" alt="{{ $room['alt'] }}"><div class="bg-surface-container-low p-4"><p class="text-xs font-semibold uppercase tracking-wider text-secondary">{{ $room['type'] }}</p><h3 class="mt-1 font-headline text-2xl text-primary">{{ $room['name'] }}</h3><p class="mt-3 text-sm text-on-surface-variant">{{ $checkIn->format('M d, Y') }} - {{ $checkOut->format('M d, Y') }}</p><p class="mt-1 text-sm text-on-surface-variant">{{ $nights }} {{ $nights === 1 ? 'night' : 'nights' }} · {{ $reservation['guests'] }} {{ $reservation['guests'] === 1 ? 'guest' : 'guests' }}</p></div></div><div class="space-y-3 border-t border-surface-container-highest pt-5 text-sm text-on-surface-variant"><div class="flex justify-between"><span>Accommodation</span><span class="text-on-surface">PHP {{ number_format($stayTotal) }}</span></div><div class="flex justify-between"><span>Resort fee</span><span class="text-on-surface">PHP {{ number_format($resortFee) }}</span></div><div class="flex justify-between"><span>Taxes</span><span class="text-on-surface">PHP {{ number_format($taxes) }}</span></div><div class="flex justify-between border-t border-surface-container-highest pt-4 font-semibold text-primary"><span>Total stay value</span><span class="font-headline text-2xl">PHP {{ number_format($stayTotal + $resortFee + $taxes) }}</span></div></div><a class="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-primary underline underline-offset-4 hover:text-secondary" href="{{ route('reservation.cart') }}">Back to reservation cart <span class="material-symbols-outlined text-base">arrow_back</span></a></div></aside>
    </div></main>
<footer class="bg-primary py-12 text-on-primary"><div class="mx-auto flex max-w-container-max flex-col justify-between gap-5 px-margin-mobile md:flex-row md:items-end md:px-margin-desktop"><div><div class="mb-3 font-headline text-2xl tracking-widest">PRAISTY</div><p class="max-w-xs text-sm text-primary-fixed">A modern sanctuary where raw nature meets refined luxury.</p></div><p class="text-sm text-primary-fixed">&copy; {{ date('Y') }} Praisty Resort &amp; Spa. All rights reserved.</p></div></footer>
<script src="{{ asset('js/app.js') }}?v=202609271430"></script>
</body>
</html>
