<!DOCTYPE html>
<html class="scroll-smooth" lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Guest Login | Praisty Resort</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms"></script>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600&amp;family=Hanken+Grotesk:wght@400;500;600;700&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet">
    <script>tailwind.config = { theme: { extend: { colors: { primary: '#002b5c', 'primary-container': '#00417e', secondary: '#3d6e38', surface: '#fbf9f4', 'surface-container-low': '#f5f3ee', 'surface-container-highest': '#e4e2dd', 'on-surface': '#1b1c19', 'on-surface-variant': '#4e535b', outline: '#737780', 'tertiary-fixed-dim': '#e9c176' }, fontFamily: { headline: ['EB Garamond', 'serif'], body: ['Hanken Grotesk', 'sans-serif'] }, spacing: { 'margin-mobile': '20px', 'margin-desktop': '64px', 'container-max': '1280px' } } } }</script>
</head>
<body class="min-h-screen bg-surface font-body text-on-surface antialiased">
    <nav class="sticky top-0 z-40 border-b border-surface-container-highest bg-surface/95 backdrop-blur"><div class="mx-auto flex max-w-container-max items-center justify-between px-margin-mobile py-4 md:px-margin-desktop"><a class="font-headline text-[28px] tracking-[0.16em] text-primary" href="{{ route('home') }}">PRAISTY RESORT</a><a class="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:text-secondary" href="{{ route('home') }}"><span class="material-symbols-outlined text-lg">arrow_back</span>Return to resort</a></div></nav>

    <main class="mx-auto max-w-container-max px-margin-mobile py-8 md:px-margin-desktop md:py-12"><div class="overflow-hidden rounded-lg bg-white shadow-xl"><div class="grid min-h-[680px] grid-cols-1 lg:grid-cols-12">
        <section class="relative flex min-h-[440px] flex-col justify-between overflow-hidden p-8 text-white lg:col-span-7 lg:min-h-full lg:p-14"><img class="absolute inset-0 h-full w-full object-cover" src="{{ asset('images/resort/hero.png') }}" alt="Praisty Resort villa at sunset"><div class="absolute inset-0 bg-gradient-to-t from-primary via-primary/75 to-primary/25"></div><div class="relative flex items-center justify-between"><span class="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-widest backdrop-blur"><span class="h-1.5 w-1.5 rounded-full bg-tertiary-fixed-dim"></span>The Praisty Circle</span><span class="hidden text-xs font-semibold uppercase tracking-widest text-white/80 sm:block">El Nido, Palawan</span></div><div class="relative my-auto max-w-xl py-12"><p class="text-xs font-semibold uppercase tracking-[0.22em] text-tertiary-fixed-dim">Private Guest Portal</p><h1 class="mt-3 font-headline text-5xl leading-[0.92] md:text-7xl">Welcome Back to Your Sanctuary.</h1><p class="mt-6 max-w-lg text-base leading-7 text-white/85">Manage upcoming stays, curate villa services, and keep every detail of your island escape within reach.</p><div class="mt-8 grid grid-cols-1 gap-3 sm:grid-cols-3"><div class="bg-white/10 p-3 backdrop-blur"><span class="material-symbols-outlined text-tertiary-fixed-dim">hotel_class</span><p class="mt-3 text-sm font-semibold">Bespoke Stays</p><p class="mt-1 text-xs text-white/75">Personal villa details</p></div><div class="bg-white/10 p-3 backdrop-blur"><span class="material-symbols-outlined text-tertiary-fixed-dim">loyalty</span><p class="mt-3 text-sm font-semibold">Circle Privileges</p><p class="mt-1 text-xs text-white/75">Seasonal benefits</p></div><div class="bg-white/10 p-3 backdrop-blur"><span class="material-symbols-outlined text-tertiary-fixed-dim">sailing</span><p class="mt-3 text-sm font-semibold">Easy Arrival</p><p class="mt-1 text-xs text-white/75">Concierge coordination</p></div></div></div><p class="relative text-xs text-white/70">Praisty Resort &amp; Spa, El Nido, Palawan</p></section>

        <section class="flex flex-col justify-center p-7 sm:p-10 lg:col-span-5 lg:p-12"><div class="mx-auto w-full max-w-md"><div class="mb-8"><div class="flex items-center gap-2 text-secondary"><span class="material-symbols-outlined text-base">verified_user</span><span class="text-xs font-semibold uppercase tracking-widest">Secure Guest Access</span></div><h2 class="mt-3 font-headline text-4xl text-primary">Access Your Stay</h2><p class="mt-2 text-sm leading-6 text-on-surface-variant">Sign in to manage your resort account and upcoming reservations.</p></div>
            @if (session('account_status'))<div class="mb-5 rounded border border-secondary/30 bg-green-50 px-4 py-3 text-sm text-secondary" role="status">{{ session('account_status') }}</div>@endif
            @if ($errors->any())<div class="mb-5 rounded border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800"><p class="font-semibold">We could not sign you in.</p><ul class="mt-1 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <form action="{{ route('guest.login.store') }}" class="space-y-5" method="POST">@csrf
                <label class="block text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Email address<div class="relative mt-2"><span class="material-symbols-outlined pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3 text-outline">alternate_email</span><input autocomplete="email" class="w-full rounded border-0 bg-surface-container-low py-3 pl-11 pr-4 text-on-surface ring-1 ring-transparent placeholder:text-outline focus:bg-white focus:ring-2 focus:ring-primary" name="email" placeholder="name@domain.com" required type="email" value="{{ old('email') }}"></div></label>
                <label class="block text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Password<div class="relative mt-2"><span class="material-symbols-outlined pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3 text-outline">lock</span><input autocomplete="current-password" class="w-full rounded border-0 bg-surface-container-low py-3 pl-11 pr-11 text-on-surface ring-1 ring-transparent placeholder:text-outline focus:bg-white focus:ring-2 focus:ring-primary" id="password" name="password" placeholder="Enter your password" required type="password"><button aria-label="Show password" class="absolute inset-y-0 right-0 px-3 text-outline hover:text-primary" id="password-toggle" type="button"><span class="material-symbols-outlined">visibility</span></button></div></label>
                <div class="flex flex-col gap-3 text-sm text-on-surface-variant sm:flex-row sm:items-center sm:justify-between"><label class="flex cursor-pointer items-center gap-2"><input class="rounded border-outline text-primary focus:ring-primary" name="remember" type="checkbox" value="1">Remember this device for 30 days</label><a class="font-semibold text-primary underline underline-offset-4 hover:text-secondary" href="{{ route('guest.password.request') }}">Forgot password?</a></div>
                <button class="flex w-full items-center justify-center gap-2 rounded bg-primary-container px-6 py-3.5 text-sm font-semibold uppercase tracking-wider text-white transition-colors hover:bg-secondary" type="submit">Sign In to Praisty<span class="material-symbols-outlined text-lg">arrow_forward</span></button>
            </form>
            <div class="my-7 flex items-center gap-3"><span class="h-px flex-1 bg-surface-container-highest"></span><span class="text-xs font-semibold uppercase tracking-widest text-outline">New to Praisty?</span><span class="h-px flex-1 bg-surface-container-highest"></span></div>
            <a class="flex w-full items-center justify-center gap-2 rounded border border-primary px-6 py-3.5 text-sm font-semibold uppercase tracking-wider text-primary transition-colors hover:bg-surface-container-low" href="{{ route('guest.register') }}">Create an Account<span class="material-symbols-outlined text-lg">person_add</span></a>
            <p class="mt-6 text-center text-xs leading-5 text-on-surface-variant"><span class="material-symbols-outlined mr-1 align-bottom text-sm text-secondary">encrypted</span>Your account information is protected with secure encryption.</p>
        </div></section>
    </div></div></main>
    <script>document.getElementById('password-toggle').addEventListener('click', function () { const password = document.getElementById('password'); const visible = password.type === 'text'; password.type = visible ? 'password' : 'text'; this.setAttribute('aria-label', visible ? 'Show password' : 'Hide password'); this.querySelector('span').textContent = visible ? 'visibility' : 'visibility_off'; });</script>
</body>
</html>
