<!DOCTYPE html>
<html class="scroll-smooth" lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Reservation Cart | Praisty Resort</title>
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..900&amp;family=Hanken+Grotesk:ital,wght@0,100..900;1,400..900&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <script>tailwind.config={theme:{extend:{colors:{background:'#fbf9f4',surface:'#fbf9f4','surface-container-low':'#f5f3ee','surface-container-high':'#eae8e3','surface-container-highest':'#e4e2dd',primary:'#001e40','primary-container':'#003366','on-primary':'#ffffff','primary-fixed':'#d5e3ff',secondary:'#3b6934','secondary-container':'#b9eeab','on-secondary-container':'#3f6d38','on-surface':'#1b1c19','on-surface-variant':'#43474f',outline:'#737780','outline-variant':'#c3c6d1','tertiary-fixed':'#ffdea5','on-tertiary-fixed-variant':'#5d4201'},spacing:{'section-gap':'120px','margin-mobile':'20px','container-max':'1280px','margin-desktop':'64px'},fontFamily:{display:['EB Garamond','serif'],headline:['EB Garamond','serif'],body:['Hanken Grotesk','sans-serif']}}}};</script>
</head>
<body class="min-h-screen bg-background font-body text-on-surface antialiased">
<nav class="fixed top-0 z-50 w-full bg-surface/90 shadow-sm backdrop-blur-md" id="main-nav"><div class="mx-auto flex max-w-container-max items-center justify-between px-margin-mobile py-4 md:px-margin-desktop"><a class="font-headline text-[28px] tracking-widest text-primary uppercase" href="{{ route('home') }}">Praisty Resort</a><div class="hidden items-center space-x-8 text-sm font-semibold tracking-wide md:flex"><a class="text-on-surface-variant hover:text-primary" href="{{ route('home') }}">Home</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('rooms') }}">Rooms &amp; Villas</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('experiences') }}">Experiences</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('gallery') }}">Gallery</a><a class="text-on-surface-variant hover:text-primary" href="{{ route('contact') }}">Contact</a></div><a class="hidden rounded bg-primary-container px-6 py-3 text-sm font-semibold uppercase tracking-wide text-on-primary md:inline-flex" href="{{ route('rooms.details', ['room' => \Illuminate\Support\Str::slug($room['name'])]) }}#reservation">Edit Stay</a><button aria-controls="mobile-menu" aria-expanded="false" aria-label="Open navigation menu" class="p-2 text-primary md:hidden" id="mobile-menu-button" type="button"><span class="material-symbols-outlined">menu</span></button></div><div class="hidden border-t border-outline-variant bg-surface px-margin-mobile py-5 md:hidden" id="mobile-menu"><div class="flex flex-col gap-4 text-sm font-semibold text-primary"><a href="{{ route('home') }}">Home</a><a href="{{ route('rooms') }}">Rooms &amp; Villas</a><a href="{{ route('experiences') }}">Experiences</a><a href="{{ route('gallery') }}">Gallery</a><a href="{{ route('contact') }}">Contact</a></div></div></nav>

<main class="mx-auto max-w-container-max px-margin-mobile pb-24 pt-28 md:px-margin-desktop md:pt-32">
    <div class="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-center"><nav aria-label="Breadcrumb" class="flex items-center gap-2 text-sm text-on-surface-variant"><a class="hover:text-primary" href="{{ route('home') }}">Home</a><span>/</span><a class="hover:text-primary" href="{{ route('rooms') }}">Rooms &amp; Villas</a><span>/</span><span class="text-primary">Reservation Cart</span></nav><div class="flex w-fit items-center gap-3 rounded-full bg-surface-container-low px-4 py-2 text-xs font-semibold"><span class="flex items-center gap-1.5 text-secondary"><span class="material-symbols-outlined text-base">check_circle</span>1. Villa Selected</span><span class="h-px w-4 bg-outline-variant"></span><span class="flex items-center gap-1.5 text-primary"><span class="flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[10px] text-on-primary">2</span>Review &amp; Add-ons</span><span class="h-px w-4 bg-outline-variant"></span><span class="text-outline">3. Guest Details</span></div></div>

    <div class="grid grid-cols-1 items-start gap-8 lg:grid-cols-12">
        <div class="space-y-8 lg:col-span-8">
            <section class="rounded-xl bg-white p-6 shadow-sm md:p-8"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="mb-2 text-xs font-semibold uppercase tracking-widest text-secondary">Step 2 of 3</p><h1 class="font-headline text-4xl text-primary md:text-5xl">Your Curated Stay</h1></div><div class="flex w-fit items-center gap-2 rounded-full bg-tertiary-fixed/30 px-3.5 py-1.5 text-xs font-semibold text-on-tertiary-fixed-variant"><span class="material-symbols-outlined animate-pulse text-base">timer</span>Cart held for <strong id="timer-display">15:00</strong></div></div></section>

            <section class="overflow-hidden rounded-xl bg-white shadow-sm"><div class="grid grid-cols-1 md:grid-cols-12"><div class="relative min-h-64 md:col-span-5"><img class="absolute inset-0 h-full w-full object-cover" src="{{ asset($room['image']) }}" alt="{{ $room['alt'] }}"><span class="absolute left-3 top-3 rounded-full bg-primary/90 px-3 py-1 text-xs font-semibold text-on-primary backdrop-blur">Primary Accommodation</span></div><div class="flex flex-col justify-between p-6 md:col-span-7 md:p-8"><div><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wider text-secondary">{{ $room['type'] }}</p><h2 class="mt-1 font-headline text-3xl text-primary">{{ $room['name'] }}</h2></div><a aria-label="Change accommodation" class="p-1 text-outline transition-colors hover:text-primary" href="{{ route('rooms') }}"><span class="material-symbols-outlined">edit</span></a></div><div class="my-5 flex flex-wrap gap-2"><span class="inline-flex items-center gap-1.5 rounded bg-surface-container-low px-3 py-1.5 text-sm"><span class="material-symbols-outlined text-base text-primary">calendar_month</span>{{ $checkIn->format('M d, Y') }} - {{ $checkOut->format('M d, Y') }} ({{ $nights }} {{ $nights === 1 ? 'Night' : 'Nights' }})</span><span class="inline-flex items-center gap-1.5 rounded bg-surface-container-low px-3 py-1.5 text-sm"><span class="material-symbols-outlined text-base text-primary">person</span>{{ $reservation['guests'] }} {{ $reservation['guests'] === 1 ? 'Guest' : 'Guests' }} · 1 Villa</span><span class="inline-flex items-center gap-1.5 rounded bg-surface-container-low px-3 py-1.5 text-sm"><span class="material-symbols-outlined text-base text-primary">{{ $room['featureIcon'] }}</span>{{ $room['feature'] }}</span></div><h3 class="mb-2 text-xs font-semibold uppercase tracking-wider text-on-surface-variant">Signature Inclusions</h3><ul class="grid grid-cols-1 gap-x-2 gap-y-1.5 text-xs sm:grid-cols-2">@foreach (['Complimentary airport transfers', 'Daily tropical breakfast', 'Welcome wellness ritual', '24/7 island butler service'] as $inclusion)<li class="flex items-center gap-1.5"><span class="material-symbols-outlined text-base text-secondary">check</span>{{ $inclusion }}</li>@endforeach</ul></div><div class="-mb-6 -mx-6 mt-6 flex flex-wrap items-center justify-between gap-3 bg-surface-container-low p-4 md:-mb-8 md:-mx-8 md:px-8"><div><span class="block text-xs text-on-surface-variant">Nightly rate: {{ $room['price'] }} x {{ $nights }} {{ $nights === 1 ? 'night' : 'nights' }}</span><span class="font-headline text-2xl text-primary">PHP {{ number_format($stayTotal) }}</span></div><a class="text-xs font-semibold uppercase tracking-wider text-primary underline underline-offset-4 hover:text-secondary" href="{{ route('rooms.details', ['room' => \Illuminate\Support\Str::slug($room['name'])]) }}#reservation">Edit dates</a></div></div></div></section>

            <section class="flex gap-3 rounded-xl bg-surface-container-high/50 p-5"><span class="material-symbols-outlined mt-0.5 text-secondary">verified_user</span><div><h3 class="font-semibold text-primary">Praisty Flexible Hospitality Guarantee</h3><p class="mt-1 text-sm text-on-surface-variant">Free cancellation and full deposit refund up to 7 days before arrival. Your dates and room choice are saved while you review your stay.</p></div></section>

            <section><div class="mb-5 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p class="mb-1 text-xs font-semibold uppercase tracking-widest text-secondary">Elevate Your Journey</p><h2 class="font-headline text-3xl text-primary">Curate Resort Experiences</h2></div><p class="text-sm text-on-surface-variant">Select any experience to add it to your stay.</p></div><div class="grid grid-cols-1 gap-4 md:grid-cols-3" id="add-on-list">
                @php $addOns = [['Sunset Beach Dining', 'Five-course seafood tasting served at a private candlelit table by the sea.', 18000, 'images/resort/praisty-sunset-dining.png', 'Dining'], ['Couples Ocean Ritual', 'A 90-minute botanical massage in a quiet oceanfront spa pavilion.', 14500, 'images/resort/sanctuary-spa.png', 'Wellness'], ['Private Island Cruise', "A relaxed private sailing experience through Palawan's limestone coves.", 22000, 'images/gallery/gallery-28.png', 'Adventure']]; @endphp
                @foreach ($addOns as [$title, $description, $price, $image, $category])<article class="overflow-hidden rounded-xl bg-white shadow-sm"><img class="h-44 w-full object-cover" src="{{ asset($image) }}" alt="{{ $title }}"><div class="flex min-h-52 flex-col p-4"><span class="text-xs font-semibold uppercase tracking-wider text-secondary">{{ $category }}</span><h3 class="mt-1 font-headline text-xl text-primary">{{ $title }}</h3><p class="mt-2 text-xs leading-5 text-on-surface-variant">{{ $description }}</p><div class="mt-auto flex items-center justify-between pt-4"><span class="text-sm font-semibold text-primary">PHP {{ number_format($price) }}</span><button class="add-on rounded bg-primary-container px-3.5 py-2 text-xs font-semibold text-on-primary transition-colors hover:bg-secondary" data-price="{{ $price }}" data-title="{{ $title }}" type="button">+ Add</button></div></div></article>@endforeach
            </div></section>
        </div>

        <aside class="lg:col-span-4"><div class="sticky top-28 rounded-xl bg-white p-6 shadow-md md:p-7"><h2 class="font-headline text-3xl text-primary">Reservation Summary</h2><div class="my-6 space-y-3 border-y border-surface-container-highest py-5 text-sm text-on-surface-variant"><div class="flex justify-between"><span>Accommodation ({{ $nights }} nights)</span><span class="text-on-surface">PHP {{ number_format($stayTotal) }}</span></div><div class="flex justify-between"><span>Resort fee</span><span class="text-on-surface">PHP {{ number_format($resortFee) }}</span></div><div class="flex justify-between"><span>Taxes</span><span class="text-on-surface">PHP {{ number_format($taxes) }}</span></div><div id="add-on-summary" class="hidden space-y-2 border-t border-surface-container-highest pt-3"></div></div><div class="rounded-lg bg-surface-container-low p-4"><div class="flex justify-between"><span class="text-sm font-semibold uppercase tracking-wider text-primary">Total stay value</span><span class="font-headline text-2xl text-primary" id="total-value" data-base="{{ $stayTotal + $resortFee + $taxes }}">PHP {{ number_format($stayTotal + $resortFee + $taxes) }}</span></div><p class="mt-2 text-xs text-on-surface-variant">No payment will be taken at this stage.</p></div><a class="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-4 text-sm font-semibold uppercase tracking-widest text-on-primary transition-all hover:scale-[1.01] hover:bg-primary-container" href="{{ route('reservation.guest-payment') }}">Continue to Guest Details <span class="material-symbols-outlined text-lg">arrow_forward</span></a><div class="mt-6 space-y-3 border-t border-surface-container-highest pt-5 text-xs text-on-surface-variant"><div class="flex items-center gap-2.5"><span class="material-symbols-outlined text-secondary">lock</span>Secure booking review</div><div class="flex items-center gap-2.5"><span class="material-symbols-outlined text-secondary">support_agent</span>24/7 island guest assistance</div></div></div></aside>
    </div>
</main>
<footer class="bg-primary py-12 text-on-primary"><div class="mx-auto flex max-w-container-max flex-col justify-between gap-5 px-margin-mobile md:flex-row md:items-end md:px-margin-desktop"><div><div class="mb-3 font-headline text-2xl tracking-widest">PRAISTY</div><p class="max-w-xs text-sm text-primary-fixed">A modern sanctuary where raw nature meets refined luxury.</p></div><p class="text-sm text-primary-fixed">&copy; {{ date('Y') }} Praisty Resort &amp; Spa. All rights reserved.</p></div></footer>
<script src="{{ asset('js/app.js') }}"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const total = document.getElementById('total-value'), summary = document.getElementById('add-on-summary'), format = value => `PHP ${new Intl.NumberFormat('en-PH').format(value)}`; let selected = [];
    document.querySelectorAll('.add-on').forEach(button => button.addEventListener('click', () => { const title = button.dataset.title, price = Number(button.dataset.price), existing = selected.find(item => item.title === title); selected = existing ? selected.filter(item => item.title !== title) : [...selected, {title, price}]; button.textContent = existing ? '+ Add' : 'Remove'; button.classList.toggle('bg-primary-container', !!existing); button.classList.toggle('bg-red-700', !existing); summary.innerHTML = selected.map(item => `<div class="flex justify-between"><span>${item.title}</span><span class="text-on-surface">${format(item.price)}</span></div>`).join(''); summary.classList.toggle('hidden', selected.length === 0); total.textContent = format(Number(total.dataset.base) + selected.reduce((sum, item) => sum + item.price, 0)); }));
    let seconds = 900; const timer = document.getElementById('timer-display'); setInterval(() => { seconds = Math.max(0, seconds - 1); timer.textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }, 1000);
});
</script>
</body>
</html>
